#!/usr/bin/zsh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/.zshenv"

if [[ "$(tty)" = "/dev/tty1" ]]; then
	pgrep i3 || startx
fi
