#!/bin/bash

current=$(setxkbmap -query | grep -i layout | awk '{print $2}')

case $current in
    'us') next='gr' ;;
    'gr') next='us' ;;
    *) next='us' ;;
esac

notify-send "Layout: $next"
setxkbmap $next
