# Inserts a blank line between shell prompts
add_newline = false

command_timeout = 100

format="$python$character$directory$git_branch$git_status"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](green) "
error_symbol = "[➜](red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = true

[cmake]
disabled = true

[cmd_duration]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true
